# See the documentation for more information:
# https://packit.dev/docs/configuration

upstream_package_name: mfem
upstream_project_url: https://github.com/mfem/mfem

downstream_package_name: mfem

specfile_path: mfem.spec

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-rawhide-aarch64
  - fedora-rawhide-i386
  - fedora-rawhide-ppc64le
  - fedora-rawhide-s390x
  - fedora-rawhide-x86_64

- job: copr_build
  trigger: release
  targets:
  - fedora-rawhide-aarch64
  - fedora-rawhide-i386
  - fedora-rawhide-ppc64le
  - fedora-rawhide-s390x
  - fedora-rawhide-x86_64
